name: Build My EXE
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          pip install .
          pip install pyinstaller
      - name: Create EXE
        run: |
          # Создаем файл через многострочный ввод, чтобы не было проблем с кавычками
          copy con run_me.py
          from rkn_block_checker.cli import main
          import sys
          if __name__ == '__main__':
              main()
          ^Z
          pyinstaller --onefile --console --name rkn_checker --collect-all rkn_block_checker run_me.py
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rkn-checker-ready
          path: dist/rkn_checker.exe
